CREATE TABLE IF NOT EXISTS celebrities (
  id INT PRIMARY KEY,
  full_name VARCHAR(160) NOT NULL,
  nickname VARCHAR(100),
  slug VARCHAR(180) NOT NULL UNIQUE,
  profile_image VARCHAR(255),
  banner_image VARCHAR(255),
  thumbnail_image VARCHAR(255),
  gallery_images TEXT,
  age INT,
  birth_date DATE,
  birthplace VARCHAR(180),
  nationality VARCHAR(100),
  height VARCHAR(40),
  zodiac_sign VARCHAR(40),
  languages TEXT,
  profession VARCHAR(180),
  years_active VARCHAR(80),
  biography TEXT,
  short_bio TEXT,
  awards TEXT,
  famous_for TEXT,
  movies_count INT DEFAULT 0,
  tv_shows_count INT DEFAULT 0,
  popularity_score DECIMAL(8,2) DEFAULT 0,
  instagram_link VARCHAR(255),
  twitter_link VARCHAR(255),
  youtube_link VARCHAR(255),
  imdb_link VARCHAR(255),
  website_link VARCHAR(255),
  followers VARCHAR(60),
  fan_rating DECIMAL(3,1) DEFAULT 0,
  trending_score DECIMAL(8,2) DEFAULT 0,
  net_worth VARCHAR(80),
  relationship_status VARCHAR(80),
  hobbies TEXT,
  favorite_movies TEXT,
  upcoming_projects TEXT,
  known_for_movies TEXT,
  featured TINYINT(1) DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_celeb_slug (slug),
  INDEX idx_celeb_popularity (popularity_score),
  INDEX idx_celeb_trending (trending_score),
  INDEX idx_celeb_country (nationality)
);

CREATE TABLE IF NOT EXISTS celebrity_comments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  celebrity_id INT NOT NULL,
  username VARCHAR(120) NOT NULL,
  rating INT DEFAULT 5,
  comment TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_celebrity_comments (celebrity_id),
  CONSTRAINT fk_celebrity_comments_celeb FOREIGN KEY (celebrity_id) REFERENCES celebrities(id) ON DELETE CASCADE
);
